# Generated by Django 3.2 on 2024-05-30 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='faultCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_code', models.CharField(max_length=32, null=True)),
                ('machine_name', models.CharField(max_length=32, null=True)),
                ('warning_time', models.CharField(max_length=32)),
                ('component_name', models.CharField(max_length=32, null=True)),
                ('fault_type', models.CharField(max_length=32)),
                ('fault_code', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='machineStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_code', models.CharField(max_length=32, null=True)),
                ('machine_name', models.CharField(max_length=32, null=True)),
                ('component_number', models.CharField(max_length=32)),
                ('component_name', models.CharField(max_length=32)),
                ('component_status', models.CharField(max_length=32)),
                ('monitor_status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='monitorValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_name', models.CharField(max_length=32)),
                ('value_unit', models.CharField(max_length=32)),
                ('value', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='sensorStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_code', models.CharField(max_length=32, null=True)),
                ('sensor_name', models.CharField(max_length=32, null=True)),
                ('sensor_status', models.CharField(max_length=32, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='thermalDiagram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_code', models.CharField(max_length=32, null=True)),
                ('machine_name', models.CharField(max_length=32, null=True)),
                ('machine_running_time', models.CharField(max_length=32)),
            ],
        ),
    ]
