# Generated by Django 3.2 on 2024-11-22 16:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='faultCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_id', models.IntegerField(null=True)),
                ('machine_code', models.CharField(max_length=32, null=True)),
                ('machine_name', models.CharField(max_length=32, null=True)),
                ('warning_time', models.CharField(max_length=32)),
                ('component_id', models.IntegerField(null=True)),
                ('component_name', models.CharField(max_length=32, null=True)),
                ('fault_type', models.CharField(max_length=32)),
                ('fault_code', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='machineParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_id', models.IntegerField(null=True)),
                ('machine_name', models.CharField(max_length=32, null=True)),
                ('machine_t', models.FloatField(max_length=32)),
                ('machine_p', models.FloatField(max_length=32)),
                ('machine_a', models.FloatField(max_length=32)),
                ('machine_t_unit', models.CharField(max_length=32)),
                ('machine_p_unit', models.CharField(max_length=32)),
                ('machine_a_unit', models.CharField(max_length=32)),
                ('machine_t_max', models.FloatField(max_length=32)),
                ('machine_p_max', models.FloatField(max_length=32)),
                ('machine_a_max', models.FloatField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='thermalDiagram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_id', models.IntegerField(null=True)),
                ('machine_code', models.CharField(max_length=32, null=True)),
                ('machine_name', models.CharField(max_length=32, null=True)),
                ('machine_process_date', models.DateField(default=django.utils.timezone.now)),
                ('machine_running_time', models.FloatField(max_length=32)),
            ],
        ),
    ]
