# Generated by Django 3.2 on 2024-11-29 03:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('systemConfig', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='componentConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_id', models.IntegerField(null=True)),
                ('component_code', models.CharField(max_length=32)),
                ('component_name', models.CharField(max_length=32, null=True)),
                ('remark', models.CharField(max_length=32, null=True)),
                ('component_status', models.BooleanField(default=0, max_length=32)),
                ('monitor_status', models.BooleanField(default=False)),
                ('current_life', models.IntegerField(null=True)),
                ('middle_value', models.IntegerField(default=40)),
                ('last_value', models.IntegerField(default=20)),
            ],
        ),
        migrations.CreateModel(
            name='componentSensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='methodConfig.componentconfig')),
                ('sensor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='systemConfig.sensorconfig')),
            ],
        ),
        migrations.CreateModel(
            name='componentAlgorithmRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_name', models.CharField(max_length=32, null=True)),
                ('algorithm_type', models.IntegerField(null=True)),
                ('sensor_name', models.CharField(max_length=32, null=True)),
                ('date', models.CharField(max_length=32, null=True)),
                ('value1', models.CharField(max_length=65535, null=True)),
                ('value2', models.CharField(max_length=65535, null=True)),
                ('value3', models.CharField(max_length=65535, null=True)),
                ('value4', models.IntegerField(null=True)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='methodConfig.componentconfig')),
            ],
        ),
        migrations.CreateModel(
            name='algorithmConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('algorithm_code', models.CharField(max_length=32, null=True)),
                ('algorithm_name', models.CharField(max_length=32, null=True)),
                ('algorithm_channel_number', models.IntegerField(null=True)),
                ('algorithm_file', models.FileField(null=True, upload_to='AlgorithmFile/')),
                ('remark', models.CharField(max_length=32, null=True)),
                ('algorithm_monitor_status', models.BooleanField(default=False)),
                ('algorithm_type', models.IntegerField(null=True)),
                ('function_name', models.CharField(max_length=32, null=True)),
                ('config', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='systemConfig.systemconfig')),
            ],
        ),
        migrations.CreateModel(
            name='algorithmChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('algorithm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='methodConfig.algorithmconfig')),
                ('channel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='systemConfig.channelconfig')),
            ],
        ),
    ]
