# Generated by Django 3.2 on 2024-11-22 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='algorithmConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('algorithm_code', models.CharField(max_length=32, null=True)),
                ('algorithm_name', models.CharField(max_length=32, null=True)),
                ('algorithm_channel_number', models.IntegerField(null=True)),
                ('algorithm_file', models.FileField(null=True, upload_to='AlgorithmFile/')),
                ('remark', models.CharField(max_length=32, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='componentConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_id', models.IntegerField(null=True)),
                ('component_code', models.CharField(max_length=32)),
                ('component_name', models.CharField(max_length=32, null=True)),
                ('remark', models.CharField(max_length=32, null=True)),
                ('component_status', models.BooleanField(default=0, max_length=32)),
                ('monitor_status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='componentSensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_id', models.IntegerField(null=True)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='methodConfig.componentconfig')),
            ],
        ),
        migrations.CreateModel(
            name='algorithmComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_id', models.IntegerField(null=True)),
                ('algorithm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='methodConfig.algorithmconfig')),
            ],
        ),
    ]
