# Generated by Django 3.2 on 2024-05-30 11:51

from django.db import migrations, models
import django.db.models.deletion


def create_initial_data(apps, schema_editor):
    Model1 = apps.get_model('methodConfig', 'algorithmConfig')
    Model2 = apps.get_model('methodConfig', 'componentConfig')
    Model3 = apps.get_model('methodConfig', 'algorithmChannel')

    Model1.objects.create(id=1, algorithm_code='SF-SVM-01', algorithm_name='主轴-SVM', algorithm_channel_number='3',
                          algorithm_file='AlgorithmFile/test.py')
    Model1.objects.create(id=2, algorithm_code='SF-DL-01', algorithm_name='主轴-DL', algorithm_channel_number='3',
                          algorithm_file='AlgorithmFile/test.py')
    Model1.objects.create(id=3, algorithm_code='SF-SVM-02', algorithm_name='减速器-SVM', algorithm_channel_number='3',
                          algorithm_file='AlgorithmFile/test.py')
    Model1.objects.create(id=4, algorithm_code='SF-DL-02', algorithm_name='减速器-DL', algorithm_channel_number='3',
                          algorithm_file='AlgorithmFile/test.py')
    Model1.objects.create(id=5, algorithm_code='SF-CNC-01', algorithm_name='减速器-CNC', algorithm_channel_number='3',
                          algorithm_file='AlgorithmFile/test.py')
    # 初始化部件-主轴
    Model2.objects.create(id=1, config_id=1, machine_code='vmc850', machine_name='大恒机床VMC850',
                          component_code='vmc850-主轴电机', component_name='主轴电机', algorithm_id=1,
                          algorithm_name='主轴-SVM', component_status='正常', monitor_status='1')
    Model2.objects.create(id=2, config_id=1, machine_code='vmc850', machine_name='大恒机床VMC850',
                          component_code='vmc850-减速器', component_name='减速器',
                          algorithm_id=3, algorithm_name='减速器-SVM', component_status='正常', monitor_status='1')

    Model3.objects.create(id=1, sensor_id=2, sensor_name='主轴-三相交流电流传感器', channel_id=4,
                          channel_name='加速度-X',
                          algorithm_channel_id=1)
    Model3.objects.create(id=2, sensor_id=2, sensor_name='主轴-三相交流电流传感器', channel_id=5,
                          channel_name='加速度-Y',
                          algorithm_channel_id=1)
    Model3.objects.create(id=3, sensor_id=2, sensor_name='主轴-三相交流电流传感器', channel_id=6,
                          channel_name='加速度-Z',
                          algorithm_channel_id=1)

    Model3.objects.create(id=4, sensor_id=2, sensor_name='主轴-三相交流电流传感器', channel_id=4, channel_name='电流-U',
                          algorithm_channel_id=2)
    Model3.objects.create(id=5, sensor_id=2, sensor_name='主轴-三相交流电流传感器', channel_id=5, channel_name='电流-V',
                          algorithm_channel_id=2)
    Model3.objects.create(id=6, sensor_id=2, sensor_name='主轴-三相交流电流传感器', channel_id=6, channel_name='电流-W',
                          algorithm_channel_id=2)


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='componentConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_id', models.IntegerField(null=True)),
                ('machine_code', models.CharField(max_length=32, null=True)),
                ('machine_name', models.CharField(max_length=32, null=True)),
                ('component_code', models.CharField(max_length=32, null=True)),
                ('component_name', models.CharField(max_length=32, null=True)),
                ('algorithm_id', models.IntegerField(null=True)),
                ('algorithm_name', models.CharField(max_length=32, null=True)),
                ('remark', models.CharField(max_length=32, null=True)),
                ('component_status', models.CharField(max_length=32, null=True)),
                ('monitor_status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='algorithmConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('algorithm_code', models.CharField(max_length=32, null=True)),
                ('algorithm_name', models.CharField(max_length=32, null=True)),
                ('algorithm_channel_number', models.IntegerField(null=True)),
                ('algorithm_file', models.FileField(null=True, upload_to='AlgorithmFile/')),
                ('remark', models.CharField(max_length=32, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='algorithmChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_id', models.IntegerField(null=True)),
                ('sensor_name', models.CharField(max_length=32, null=True)),
                ('channel_id', models.IntegerField(null=True)),
                ('channel_name', models.CharField(max_length=32, null=True)),
                ('algorithm_channel',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='methodConfig.componentconfig')),
            ],
        ),
        migrations.RunPython(create_initial_data),
    ]
