# Generated by Django 3.2 on 2024-11-29 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('methodConfig', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='componentalgorithmrecord',
            name='value5',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='componentconfig',
            name='current_life',
            field=models.IntegerField(default=100),
        ),
    ]
