# Generated by Django 3.2 on 2024-11-22 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('methodConfig', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='algorithmcomponent',
            old_name='component_id',
            new_name='channel_id',
        ),
    ]
