# Generated by Django 3.2 on 2024-11-29 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('methodConfig', '0002_auto_20241129_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componentalgorithmrecord',
            name='value1',
            field=models.CharField(max_length=999999, null=True),
        ),
        migrations.AlterField(
            model_name='componentalgorithmrecord',
            name='value2',
            field=models.CharField(max_length=999999, null=True),
        ),
        migrations.AlterField(
            model_name='componentalgorithmrecord',
            name='value3',
            field=models.CharField(max_length=999999, null=True),
        ),
    ]
