# Generated by Django 3.2 on 2024-11-22 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('methodConfig', '0002_rename_component_id_algorithmcomponent_channel_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='algorithmComponent',
            new_name='algorithmChannel',
        ),
    ]
