# Generated by Django 3.2 on 2024-11-22 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('systemConfig', '0002_auto_20241123_0111'),
        ('methodConfig', '0003_rename_algorithmcomponent_algorithmchannel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='algorithmchannel',
            name='channel_id',
        ),
        migrations.AddField(
            model_name='algorithmchannel',
            name='channel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='systemConfig.channelconfig'),
        ),
    ]
