# Generated by Django 3.2 on 2024-11-22 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('systemConfig', '0002_auto_20241123_0111'),
        ('methodConfig', '0004_auto_20241123_0119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componentsensor',
            name='sensor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='systemConfig.sensorconfig'),
        ),
    ]
