# Generated by Django 3.2 on 2024-11-28 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('systemConfig', '0002_auto_20241123_0111'),
        ('methodConfig', '0005_alter_componentsensor_sensor_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='componentsensor',
            name='sensor_id',
        ),
        migrations.AddField(
            model_name='algorithmconfig',
            name='config',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='systemConfig.systemconfig'),
        ),
    ]
