# Generated by Django 3.2 on 2024-11-28 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('methodConfig', '0006_auto_20241128_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='componentconfig',
            name='last_value',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='componentconfig',
            name='middle_value',
            field=models.IntegerField(default=40),
        ),
        migrations.AddField(
            model_name='componentconfig',
            name='x_axis',
            field=models.CharField(max_length=65535, null=True),
        ),
        migrations.AddField(
            model_name='componentconfig',
            name='y_last_axis',
            field=models.CharField(max_length=65535, null=True),
        ),
        migrations.AddField(
            model_name='componentconfig',
            name='y_pre_axis',
            field=models.CharField(max_length=65535, null=True),
        ),
    ]
