# Generated by Django 3.2 on 2024-11-28 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('methodConfig', '0007_auto_20241128_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='algorithmconfig',
            name='algorithm_monitor_status',
            field=models.BooleanField(default=False),
        ),
    ]
