# Generated by Django 3.2 on 2024-05-30 10:29

from django.db import migrations, models
import django.db.models.deletion


def create_initial_data(apps, schema_editor):
    Model1 = apps.get_model('systemConfig', 'systemConfig')
    Model2 = apps.get_model('systemConfig', 'sensorConfig')
    Model3 = apps.get_model('systemConfig', 'channelConfig')
    # 初始化系统配置1
    Model1.objects.create(id=1, machine_code='vmc850', machine_name='大恒机床VMC850', machine_type='五轴加工中心',
                          machine_description='大恒机床-五轴-VMC850', manager='张三', machine_ip='192.168.110.23',
                          machine_port=7798, tool_number=30, database_name='testdata',
                          alarm_data_delay_positive=30, alarm_data_delay_negative=10,
                          machine_image='Machine/MachineImage/test.png', is_apply=1)
    # 初始化加速度传感器
    Model2.objects.create(id=1, sensor_code="C2310020216", sensor_name='XM减速器-三相加速度', frequency=10,
                          sensor_port=1030, channel_number=9, command_code='01 03 A6 04 00 09 E6 85',
                          sensor_status=1, measurement='signal', time_out=5, receive_number=46,
                          sensor_image='Sensor/SensorImage/test.png', operational_status=True, config_id=1)
    Model3.objects.create(id=1, sensor_name="XM减速器-三相加速度", channel_name='X-轴速度有效值', overrun_times=3,
                          channel_field='AcceleratedSpeed_X', unit='mm/s', is_monitor=1, channel_id=1)
    Model3.objects.create(id=2, sensor_name="XM减速器-三相加速度", channel_name='Y-轴速度有效值', overrun_times=3,
                          channel_field='AcceleratedSpeed_Y', unit='mm/s', is_monitor=1, channel_id=1)
    Model3.objects.create(id=3, sensor_name="XM减速器-三相加速度", channel_name='Z-轴速度有效值', overrun_times=3,
                          channel_field='AcceleratedSpeed_Z', unit='mm/s', is_monitor=1, channel_id=1)
    Model3.objects.create(id=4, sensor_name="XM减速器-三相加速度", channel_name='X-轴加速度标准差值', overrun_times=3,
                          channel_field='AcceleratedSpeed_X', unit='m/s²', is_monitor=1, channel_id=1)
    Model3.objects.create(id=5, sensor_name="XM减速器-三相加速度", channel_name='Y-轴加速度标准差值', overrun_times=3,
                          channel_field='AcceleratedSpeed_Y', unit='m/s²', is_monitor=1, channel_id=1)
    Model3.objects.create(id=6, sensor_name="XM减速器-三相加速度", channel_name='Z-轴加速度标准差值', overrun_times=3,
                          channel_field='AcceleratedSpeed_Z', unit='m/s²', is_monitor=1, channel_id=1)
    Model3.objects.create(id=7, sensor_name="XM减速器-三相加速度", channel_name='X-轴加速度均方根值', overrun_times=3,
                          channel_field='AcceleratedSpeed_X', unit='m/s²', is_monitor=1, channel_id=1)
    Model3.objects.create(id=8, sensor_name="XM减速器-三相加速度", channel_name='Y-轴加速度均方根值', overrun_times=3,
                          channel_field='AcceleratedSpeed_Y', unit='m/s²', is_monitor=1, channel_id=1)
    Model3.objects.create(id=9, sensor_name="XM减速器-三相加速度", channel_name='Z-轴加速度均方根值', overrun_times=3,
                          channel_field='AcceleratedSpeed_Z', unit='m/s²', is_monitor=1, channel_id=1)


class Migration(migrations.Migration):
    initial = True
    dependencies = [
    ]
    operations = [
        migrations.CreateModel(
            name='sensorConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_code', models.CharField(max_length=32, null=True)),
                ('sensor_name', models.CharField(max_length=32, null=True)),
                ('frequency', models.IntegerField(null=True)),
                ('channel_number', models.IntegerField(null=True)),
                ('command_code', models.CharField(max_length=32, null=True)),
                ('remark', models.CharField(max_length=32, null=True)),
                ('measurement', models.CharField(max_length=32, null=True)),
                ('sensor_status', models.BooleanField(default=2)),
                ('operational_status', models.BooleanField(default=True)),
                ('thread_flag', models.BooleanField(default=True)),
                ('sensor_port', models.IntegerField(null=True)),
                ('time_out', models.IntegerField(null=True)),
                ('receive_number', models.IntegerField(null=True)),
                ('config_id', models.IntegerField(default=1, null=True)),
                ('sensor_image', models.ImageField(null=True, upload_to='Sensor/')),

            ],
        ),
        migrations.CreateModel(
            name='systemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_code', models.CharField(max_length=32, null=True)),
                ('machine_name', models.CharField(max_length=32, null=True)),
                ('machine_type', models.CharField(max_length=32, null=True)),
                ('machine_description', models.CharField(max_length=32, null=True)),
                ('manager', models.CharField(max_length=32, null=True)),
                ('machine_ip', models.CharField(max_length=32, null=True)),
                ('machine_port', models.IntegerField(null=True)),
                ('tool_number', models.IntegerField(null=True)),
                ('database_name', models.CharField(max_length=32, null=True)),
                ('alarm_data_delay_positive', models.IntegerField(null=True)),
                ('alarm_data_delay_negative', models.IntegerField(null=True)),
                ('is_apply', models.BooleanField(default=0)),
                ('machine_image', models.ImageField(null=True, upload_to='MachineImage/')),  # 机床图片
            ],
        ),
        migrations.CreateModel(
            name='channelConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_code', models.CharField(max_length=32, null=True)),
                ('sensor_name', models.CharField(max_length=32, null=True)),
                ('channel_name', models.CharField(max_length=32, null=True)),
                ('overrun_times', models.IntegerField(null=True)),
                ('channel_field', models.CharField(max_length=32, null=True)),
                ('is_monitor', models.BooleanField(default=False)),
                ('unit', models.CharField(max_length=32, null=True)),
                ('remark', models.CharField(max_length=32, null=True)),
                ('channel',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='systemConfig.sensorconfig')),
            ],
        ),
        migrations.RunPython(create_initial_data),
    ]
