# Generated by Django 3.2 on 2024-11-29 03:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sensorConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_code', models.CharField(max_length=32, null=True)),
                ('sensor_name', models.CharField(max_length=32, null=True)),
                ('frequency', models.IntegerField(null=True)),
                ('channel_number', models.IntegerField(null=True)),
                ('measurement', models.CharField(max_length=32, null=True)),
                ('remark', models.CharField(max_length=32, null=True)),
                ('sensor_status', models.BooleanField(default=0)),
                ('thread_flag', models.BooleanField(default=0)),
                ('time_out', models.IntegerField(null=True)),
                ('receive_number', models.IntegerField(null=True)),
                ('sensor_image', models.ImageField(null=True, upload_to='Sensor/SensorImage/')),
                ('sensor_port', models.IntegerField(null=True)),
                ('command_code', models.CharField(max_length=32, null=True)),
                ('config_id', models.CharField(max_length=32, null=True)),
                ('ruler', models.CharField(max_length=32, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='systemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_code', models.CharField(max_length=32, null=True)),
                ('machine_name', models.CharField(max_length=32, null=True)),
                ('machine_type', models.CharField(max_length=32, null=True)),
                ('machine_description', models.CharField(max_length=32, null=True)),
                ('manager', models.CharField(max_length=32, null=True)),
                ('machine_ip', models.CharField(max_length=32, null=True)),
                ('machine_port', models.IntegerField(null=True)),
                ('tool_number', models.IntegerField(null=True)),
                ('database_name', models.CharField(max_length=32, null=True)),
                ('alarm_data_delay_positive', models.IntegerField(null=True)),
                ('alarm_data_delay_negative', models.IntegerField(null=True)),
                ('is_apply', models.BooleanField(default=0)),
                ('machine_image', models.ImageField(null=True, upload_to='Machine/MachineImage/')),
                ('detect_ident', models.IntegerField(null=True)),
                ('influx_clean_date', models.CharField(max_length=32, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='influxDataConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=32, null=True)),
                ('influx_file', models.FileField(null=True, upload_to='Sensor/SensorData/')),
                ('remark', models.CharField(max_length=32, null=True)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='systemConfig.sensorconfig')),
            ],
        ),
        migrations.CreateModel(
            name='channelConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_name', models.CharField(max_length=32, null=True)),
                ('unit', models.CharField(max_length=32, null=True)),
                ('channel_field', models.CharField(max_length=32, null=True)),
                ('remark', models.CharField(max_length=32, null=True)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='systemConfig.sensorconfig')),
            ],
        ),
    ]
