# Generated by Django 3.2 on 2024-11-22 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('systemConfig', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channelconfig',
            name='sensor_code',
        ),
        migrations.RemoveField(
            model_name='channelconfig',
            name='sensor_name',
        ),
    ]
