# Generated by Django 3.2 on 2024-11-28 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemConfig', '0002_auto_20241123_0111'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensorconfig',
            name='overrun_times',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sensorconfig',
            name='operational_status',
            field=models.IntegerField(default=0),
        ),
    ]
