# Generated by Django 3.2 on 2024-11-28 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('systemConfig', '0003_auto_20241128_1408'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channelconfig',
            name='channel_threshold',
        ),
        migrations.RemoveField(
            model_name='channelconfig',
            name='overrun_times',
        ),
    ]
